mes=[
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]
busqueda=mes.index("April")
print(busqueda+1)
#print(mes.index("April"))